# Generated by Django 4.2.30 on 2026-04-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cell_tower_id', models.CharField(max_length=50)),
                ('cell_tower_name', models.CharField(max_length=100)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'customer_coordinates',
                'indexes': [models.Index(fields=['customer_id'], name='customer_co_custome_0cf64d_idx'), models.Index(fields=['cell_tower_id'], name='customer_co_cell_to_d1e1e8_idx')],
            },
        ),
    ]
