# Generated by Django 4.2.30 on 2026-04-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HBBCustomer',
            fields=[
                ('customer_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('msisdn', models.CharField(blank=True, max_length=20)),
                ('custom1', models.CharField(blank=True, max_length=100)),
                ('custom2', models.CharField(blank=True, max_length=100)),
                ('custom8', models.CharField(blank=True, max_length=100)),
                ('billing_day', models.IntegerField(blank=True, null=True)),
                ('custom3_cells', models.TextField(blank=True, help_text='Cell IDs assigned to customer (comma-separated)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hbb_customers',
                'indexes': [models.Index(fields=['customer_id'], name='hbb_custome_custome_afc0fe_idx'), models.Index(fields=['msisdn'], name='hbb_custome_msisdn_d7bec5_idx')],
            },
        ),
    ]
